import "./(pages)/globals.css";
import Header from "@/component/partial/Header";
import Footer from "@/component/partial/Footer";
import { fetchFromStrapi } from "@/lib/strapi";

async function getFooterData() {
  try {
    const params = new URLSearchParams({
      'populate[topStats]': '*',
      'populate[brandSection][populate][logo][fields]': 'url',
      'populate[columns][populate][links]': '*',
      'populate[bottomBar][populate][policyLinks]': '*',
      'populate[bottomBar][populate][socialLinks][populate][icon][fields]': 'url',
    });
    const url = `/api/footer?${params.toString()}&publicationState=live`;
    const response = await fetchFromStrapi(url, { revalidate: 0 });
    
    if (!response) {
      return null;
    }
    
    const entry = response?.data || null;
    
    if (!entry || !entry.publishedAt) {
      return null;
    }
    
    return {
      topStats: entry?.topStats || [],
      brandSection: entry?.brandSection,
      columns: entry?.columns || [],
      bottomBar: entry?.bottomBar,
    };
  } catch (error) {
    console.error('Error fetching footer data:', error);
    return null;
  }
}

async function getHeaderData() {
  try {
    const url = `/api/header?populate[0]=logo&populate[1]=menus.dropdownList.children.children&publicationState=live`;
    const response = await fetchFromStrapi(url, { revalidate: 0 });
    
    if (!response) {
      return null;
    }
    
    const entry = response?.data || null;
    
    if (!entry || !entry.publishedAt) {
      return null;
    }
    
    return {
      logo: entry?.logo,
      menus: entry?.menus || [],
      ctaText: entry?.ctaText || '',
      ctaLink: entry?.ctaLink || '',
    };
  } catch (error) {
    console.error('Error fetching header data:', error);
    return null;
  }
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const footerData = await getFooterData();
  const headerData = await getHeaderData();
  
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Header data={headerData}/>
        {children}
        <Footer data={footerData}/>
      </body>
    </html>
  );
}

